name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the repo, and thank you for your first contribution! 🌟 We appreciate your support. A maintainer will review your input shortly. If you need to make any quick edits, feel free to drop them right here in the comments. Have a great day!"
        pr-message: "Welcome to the repo, and thank you for your first contribution! 🌟 We appreciate your support. A maintainer will review your input shortly. If you need to make any quick edits, feel free to drop them right here in the comments. Have a great day!"
